### PR TITLE
LPS-152497 - Fix some Poshi tests

### PR DESCRIPTION
**Pull request by evanilson-santana**
https://issues.liferay.com/browse/LPS-160178
https://issues.liferay.com/browse/LPS-148091
https://issues.liferay.com/browse/LPS-152497
https://issues.liferay.com/browse/LPS-152494

### CODE REVIEW

**Comment by evanilson-santana** [comment]
ci:forward

**Comment by evanilson-santana** [comment]
ci:forward

**Comment by michaelhashimoto** [comment]
ci:forward

**Comment by evanilson-santana** [comment]
ci:forward

**Comment by evanilson-santana** [comment]
ci:forward

**Comment by evanilson-santana** [comment]
ci:forward

**Pull request closed without merging**
