### PR TITLE
LPS-166001

### PR DESCRIPTION
**Pull request by evanilson-santana**

### CODE REVIEW

**Comment by evanilson-santana** [comment]
ci:test:object:nocompile

**Comment by timpak** [comment]
@evanilson-santana, do this next time with the properties.

Remove:
```test.batch.class.names.includes[object]=\
        **/object/**/*Test.java
```

Set `test.batch.names[object]=functional-tomcat90-mysql57-jdk8`

**Comment by evanilson-santana** [comment]
ci:test:object:nocompile

**Comment by evanilson-santana** [comment]
ci:test:object:nocompile

**Comment by timpak** [comment]
@evanilson-santana sorry the formatting of my comment got messed up. The test suite should look like this:
```
    #
    # Object
    #

    test.batch.dist.app.servers[object]=tomcat

    test.batch.names[object]=functional-tomcat90-mysql57-jdk8

    test.batch.run.property.query[functional-tomcat90-mysql57-jdk8][object]=\
        (\
            (portal.acceptance != quarantine) AND \
            (portal.upstream != quarantine)\
        ) AND \
        (\
            (testray.component.names ~ "Object") OR \
            (testray.main.component.name ~ "Object")\
        ) AND \
        (portal.acceptance == Test_Permission_Path)
```

**Comment by timpak** [comment]
That should force the test suite to only run Objects functional tests that aren't quarantined and have that portal.acceptance property.

**Comment by evanilson-santana** [comment]
ci:test:object:nocompile

**Pull request closed without merging**
