### PR TITLE
LPS-185427

### PR DESCRIPTION
**Pull request by evanilson-santana**
https://issues.liferay.com/browse/LPS-162130

### CODE REVIEW

**Comment by timpak** [comment]
ci:test:object

**Comment by timpak** [comment]
Hey @evanilson-santana, the tests aren't passing on CI, can you take a look? It looks like Salesforce isn't enabled in the bundle, we probably need to include the feature flag for the story. Can you try this and run the tests on CI to confirm? Unfortunately, I couldn't get the tests to work locally so we need to run them on CI.

If the tests pass, can you combine these with https://github.com/liferay-objects/liferay-portal/pull/2156 and forward it?

**Comment by evanilson-santana** [comment]
ci:test:object

**Comment by evanilson-santana** [comment]
PR resent [here](https://github.com/liferay-objects/liferay-portal/pull/2164)

**Pull request closed without merging**
